### ISSUE TITLE
Naming fields reorder

### ISSUE THREAD

**Issue by vualeks** [tmorcinek/android-codegenerator-plugin-intellij#18]
Hi,

i have a suggestion for an enhancement. Could you add a feature to name fields in reverse order of words from names in XML?

For example, if a field in XML is called activity_login_button_check to name it in code checkButtonLoginActivity?

**Comment by vualeks** [comment]
Never mind, I went on and rearranged it myself. If anyone else maybe needs something like this, changes are in android-codegenerator-library (not here in plugin), in AbstractResourceProvider.java, method getResourceName. Insert this part:

String[] tempSplit = idName.split("_");
StringBuilder tempBuilder = new StringBuilder();
for (int i = 0; i < tempSplit.length; i++)
{
        tempBuilder.append(tempSplit[tempSplit.length - i - 1]);
        tempBuilder.append("_");
}
idName = tempBuilder.toString().substring(0, tempBuilder.toString().length() - 1);

in between lines 

String idName = resource.getResourceId().getName();

and 

StringBuilder stringBuilder = new StringBuilder();

to reorder the words.

**Comment by tmorcinek** [comment]
Hi, 

I try to implement and release a new version in the beginning of November. I will think about this as a potential feature.

**Comment by tmorcinek** [comment]
Not implementing this feature. Because there was not many requests.
