### ISSUE TITLE
Invalid byte 2 of 2-byte UTF-8 sequence. (No <inlude> layout support)

### ISSUE THREAD

**Issue by AlexAndriichenko** [tmorcinek/android-codegenerator-plugin-intellij#21]
Error occurs when I click generate "Generage code" for layout with tag <include layout="@layout/..."/>

![image](https://cloud.githubusercontent.com/assets/6390479/14566560/b37eda3e-0338-11e6-8ded-663921b772da.png)

Can you add <include>  tag support?
Please:)

**Comment by tmorcinek** [comment]
Hi, this plugin supports <include> tag. The error is related to some other issue. Maybe its related to: 
Invalid byte 1 of 1-byte UTF-8 sequence. #20

**Comment by AlexAndriichenko** [comment]
Yes. The error is related to russian chars in xml. All works fine after extracting strings to strings.xml
