### ISSUE TITLE
The generated file does not correct after i edited the name in preview window

### ISSUE THREAD

**Issue by jaychang0917** [tmorcinek/android-codegenerator-plugin-intellij#22]
This is a great plugin. However, i found this issue after i changed the activity name in the preview window.

**Comment by jaychang0917** [comment]
Moreover, the Adapter template in the preference setting also have this issue. For example, I modified the Adapter template to `public class ${CLASS_NAME}Cell extends RecyclerCell {....`, but the generated file still name XXXAdapter (assume my xml file name is XXX).

**Comment by tmorcinek** [comment]
You are right, for now there is now way to change generated file name? 
Would you like to have such option implemented?

**Comment by jaychang0917** [comment]
no way to change generated file name? what do you mean?
This feature is cool, I usually change the filename since the default one extracted from the xml layout file is not what i want.

**Comment by tmorcinek** [comment]
I meant that the plugin doesn't change the name of the file automatically if you change the template. I will  create a story for this issue, and when I have time I will try to implement it.

**Comment by tmorcinek** [comment]
Created separate story for this issue.
