### ISSUE TITLE
Doesn't work for xml layout including <include>

### ISSUE THREAD

**Issue by jaychang0917** [tmorcinek/android-codegenerator-plugin-intellij#23]
Seems that it cannot retrieve the content of included layout using `<include>`.

**Comment by tmorcinek** [comment]
This functionality is not implemented but I think would be very useful. 
Thanks, I will put this feature as a priority.

**Comment by tmorcinek** [comment]
Created separate story for this issue.

**Comment by ranzhenxing** [comment]
<include
        android:id="@+id/title_bar"
        layout="@layout/style_actionbar_normal" />
if I add android:id="@+id/title_bar".the result will be abnormal too.
