### ISSUE TITLE
can't recognize layout-mdpi dir 

### ISSUE THREAD

**Issue by zhuruyi2013** [tmorcinek/android-codegenerator-plugin-intellij#29]
how can i expand codegenerator to recognise layout-xx dir?

**Comment by tmorcinek** [comment]
This is not available. But anyway, if you want to use specific 'layout-xx' dir you also need to have 'layout' folder, and respective files needs to have the same view ids for the activity to work. So there is no need for the plugin to work for different folders then 'layout'. 
Does that sound logical, or you have some other problems?
